### ISSUE TITLE
Cadastro de alarme

### ISSUE THREAD

**Issue by victoralvesgomide** [victoralvesgomide/lumus_tdd#2]
Eu, como usuário, desejo ter uma tela para o cadastro do alarme, para que eu possa definir o alarme.

- [x] Deve conter um campo de tempo para definir quando o alarme irá despertar;
- [x] Deve conter um botão para definir alarme;
- [x] Deve ser salvo o alarme na lista de alarmes após pressionar o botão;
- [x] Deve retornar à tela inicial.

**Comment by cjjcastro** [comment]
Retornar a tela inicia se tornou desnecessario, pois o prototipo que foi definido possui a tele inicial dos alarmes junto com a tela de cadastro.
