### ISSUE TITLE
Marcador

### ISSUE THREAD

**Issue by victoralvesgomide** [victoralvesgomide/lumus_tdd#3]
Eu, como usuário, desejo poder adicionar comentários ao meu alarme, para que possa me lembrar o motivo de eu criar o alarme.

- [x] Deve haver um campo de texto permitindo entrada do usuário;
- [x] Essa entrada deve ser salva;
- [x] O texto deve ser mostrado ao usuário quando o tempo do alarme acabar.

**Comment by cjjcastro** [comment]
O terceiro criterio nao e possivel de ser feito no momento, pois e necessario que outras funcionalidades sejam implementadas para tornar isso possivel.
